# Generated by Django 4.2.4 on 2023-09-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='alias',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
