# Generated by Django 4.2.4 on 2023-09-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
