# Generated by Django 4.2.4 on 2023-09-03 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_cart_total_price_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
