# Generated by Django 4.2.4 on 2023-08-29 16:23

import Utilities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=40)),
                ('image', models.ImageField(upload_to=Utilities.models.generate_image_filename)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
