# Generated by Django 4.2.4 on 2023-09-13 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expire',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
