# Generated by Django 4.2.4 on 2023-09-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_alter_coupon_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
