# Generated by Django 4.2.4 on 2023-08-29 16:23

import Utilities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to=Utilities.models.generate_image_filename),
        ),
    ]
