# Generated by Django 4.2.4 on 2023-09-05 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_myuser_username'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(limit_choices_to=models.Q(('user', models.F('user'))), on_delete=django.db.models.deletion.CASCADE, to='users.useraddress'),
        ),
    ]
