# Generated by Django 4.2.4 on 2023-09-10 18:46

import Utilities.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_rename_owner_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='color',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='products.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='imageCover',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=Utilities.models.generate_image_filename),
        ),
    ]
