# Generated by Django 4.2.4 on 2023-09-12 09:54

import Utilities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_color_name_alter_color_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='imageCover',
            field=models.ImageField(default=1, upload_to=Utilities.models.generate_image_filename),
            preserve_default=False,
        ),
    ]
