# Generated by Django 4.2.4 on 2023-09-15 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_user_alter_product_users_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
